rgb_dir: /path/to/rgb
depth_dir: /path/to/depth
traj_path: /path/to/traj.txt
yolo_model: /path/to/yoloe-11l-seg-pf.pt
conf: 0.25
iou: 0.5
kernel_size: 17
alpha: 0.7
max_points_per_obj: 2000
max_accumulated_points: 10000
fast_mask: true
o3_nb_neighbors: 50
o3std_ratio: 0.1
tracker_cfg: botsort.yaml
device: "0"
edge_predictor: sceneverse
vis_graph: false
show_pcds: false
print_resource_usage: false
print_tracking_info: false
tracking_overlap_threshold: 0.3
tracking_distance_threshold: 0.5
tracking_inactive_limit: 0
tracking_volume_ratio_threshold: 0.1
reprojection_visibility_threshold: 0.2
scene_path: null
